name: Publish to PyPI

on:
  workflow_dispatch:
  push:
    tags:
      - "v*"

jobs:
  publish:
    name: Build and publish
    runs-on: ubuntu-latest
    permissions:
      id-token: write  # Required for trusted publishing to PyPI
    steps:
      - uses: actions/checkout@v4
      - uses: astral-sh/setup-uv@v5
        with:
          python-version: "3.13"

      - name: Build portcullis
        run: uv build --package portcullis
      - name: Build portcullis-example
        run: uv build --package portcullis-example

      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          packages-dir: dist/
